{
 "title": "OLT VSOL GPON",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "usuario",
    "label": "Selecione Usuário",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Consolidado Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:685",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:686",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total Autorizadas" ],
       "text": "setAlias(Total Autorizadas)"
      }
     ],
     "group": { "filter": "OLT VSOL" },
     "host": { "filter": "OLT VSOL GPON" },
     "item": { "filter": "/.*ONUs PON/" },
     "itemTag": { "filter": "Application: Atividade" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:662",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:663",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total Onlines" ],
       "text": "setAlias(Total Onlines)"
      }
     ],
     "group": { "filter": "OLT VSOL" },
     "host": { "filter": "OLT VSOL GPON" },
     "item": { "filter": "/.ONLINE/" },
     "itemTag": { "filter": "Application: Atividade" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:685",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:686",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total Offline" ],
       "text": "setAlias(Total Autorizadas)"
      }
     ],
     "group": { "filter": "OLT VSOL" },
     "host": { "filter": "OLT VSOL GPON" },
     "item": { "filter": "ONUs OFFLINE" },
     "itemTag": { "filter": "Application: Atividade" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "options": {
    "content": "<center><img style=\" width=\"100\" height=\"100\" \" src=\"https://144ec3eb15.cbaul-cdnwnd.com/5a9cf19d5bf8c6bd7cb4b5b01c3cf4ac/200000057-2d8782d87d/LOGO-GABRIEL-B.webp?ph=144ec3eb15\" ></center>\n<p>\n<center><h3> GABRIEL TEIXEIRA CONSULTORIA </h3></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Monitoramento Geral",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "OLT VSOL" },
     "host": { "filter": "OLT VSOL GPON" },
     "item": { "filter": "CPU" },
     "itemTag": { "filter": "Application: Sistema" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "OLT VSOL" },
     "host": { "filter": "OLT VSOL GPON" },
     "item": { "filter": "RAM" },
     "itemTag": { "filter": "Application: Sistema" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "OLT VSOL" },
     "host": { "filter": "OLT VSOL GPON" },
     "item": { "filter": "Temperatura" },
     "itemTag": { "filter": "Application: Sistema" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "OLT VSOL" },
     "host": { "filter": "OLT VSOL GPON" },
     "item": { "filter": "Uptime" },
     "itemTag": { "filter": "Application: Sistema" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "ONUs Autorizadas por PON",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "OLT VSOL" },
     "host": { "filter": "OLT VSOL GPON" },
     "item": { "filter": "/.*ONUs PON/" },
     "itemTag": { "filter": "Application: Atividade" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "ONUs Onlines por PON",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "OLT VSOL" },
     "host": { "filter": "OLT VSOL GPON" },
     "item": { "filter": "/.ONLINE/" },
     "itemTag": { "filter": "Application: Atividade" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Tabela de Potencias",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "OLT VSOL" },
     "host": { "filter": "OLT VSOL GPON" },
     "item": { "filter": "$usuario" },
     "itemTag": { "filter": "Application: Potencia" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Tabela de Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "OLT VSOL" },
     "host": { "filter": "OLT VSOL GPON" },
     "item": { "filter": "$usuario" },
     "itemTag": { "filter": "Application: Atividade" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Tráfego de Uplink",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Data Center" },
     "host": { "filter": "BNG_SSP_SMARTTELECOM" },
     "item": {
      "filter": "In interface sfp-sfpplus1 #OLT VSOL GPON"
     },
     "itemTag": { "filter": "Interfaces" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "Data Center" },
     "host": { "filter": "BNG_SSP_SMARTTELECOM" },
     "item": {
      "filter": "Out interface sfp-sfpplus1 #OLT VSOL GPON"
     },
     "itemTag": { "filter": "Interfaces" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  }
 ]
}